### PR TITLE
geforce experience updates

### PR DESCRIPTION
**Pull request by AeliusSaionji**
If you are no longer interested in maintaining, please add me as a maintainer on chocolatey: LinkSatonaka

### CODE REVIEW

**Comment by okhoshi** [comment]
@Link-Satonaka Oops sorry for the lack of response, I didn't get any notification from Github for your PR

**Comment by AeliusSaionji** [comment]
Hello! Chocolatey added me as a maintainer, I've already submitted this earlier today (with iconUrl).

FYI, GeForce Experience won't install without an NVIDIA card in the PC so the package has been granted exemption from the automatic verifier.

**Comment by Link-Satonaka** [comment]
tall without NVIDIA hardware, so the package has been granted automated verifier exemption

**Comment by AeliusSaionji** [comment]
https://github.com/Link-Satonaka/chocopkgs/tree/master/GeForce-Experience

Is the latest package source

**Comment by okhoshi** [comment]
Ok, I saw your last submission and the special grant (I received the mail from Chocolatey tho) On which repo do you prefer to work  ? Yours I assume ?

**Comment by AeliusSaionji** [comment]
If you don't mind. I'm not very good at git and making PRs

**Comment by okhoshi** [comment]
Ok no problem ;) I will let you manage GeForce-Experience then. Are your Ketarin tasks running periodicaly or by hand ?

**Comment by AeliusSaionji** [comment]
Periodically

**Pull request closed without merging**
